# Generated by Django 3.2.5 on 2021-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_addresslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresslink',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
    ]
