# Generated by Django 3.2.4 on 2021-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admincontactphones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_img.jpeg', upload_to='profile_pics', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cafedra',
            field=models.CharField(max_length=300, verbose_name='cafedra'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(max_length=300, verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(max_length=200, verbose_name='level'),
        ),
    ]
