# Generated by Django 3.1 on 2021-08-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210815_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cafedra_en',
            field=models.CharField(max_length=300, null=True, verbose_name='cafedra'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cafedra_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='cafedra'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cafedra_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='cafedra'),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty_en',
            field=models.CharField(max_length=300, null=True, verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level_en',
            field=models.CharField(max_length=200, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='level'),
        ),
    ]
