# Generated by Django 3.2.4 on 2021-07-29 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_works.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension], verbose_name='File')),
                ('file_uz', models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension], verbose_name='File')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension], verbose_name='File')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension], verbose_name='File')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='projects', verbose_name='File')),
                ('file_uz', models.FileField(blank=True, null=True, upload_to='projects', verbose_name='File')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='projects', verbose_name='File')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='projects', verbose_name='File')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Presentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='presentations', verbose_name='File')),
                ('file_uz', models.FileField(blank=True, null=True, upload_to='presentations', verbose_name='File')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='presentations', verbose_name='File')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='presentations', verbose_name='File')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='events', verbose_name='File')),
                ('file_uz', models.FileField(blank=True, null=True, upload_to='events', verbose_name='File')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='events', verbose_name='File')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='events', verbose_name='File')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='books', verbose_name='File')),
                ('file_uz', models.FileField(blank=True, null=True, upload_to='books', verbose_name='File')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='books', verbose_name='File')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='books', verbose_name='File')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='name')),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='name')),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='name')),
                ('file', models.FileField(blank=True, null=True, upload_to='articles', verbose_name='File')),
                ('file_uz', models.FileField(blank=True, null=True, upload_to='articles', verbose_name='File')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='articles', verbose_name='File')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='articles', verbose_name='File')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
