# Generated by Django 3.2.4 on 2021-06-29 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('articles', 'Maqolalar'), ('books', 'Kitoblar'), ('events', 'Tadbirlar'), ('presentations', 'Taqdimotlar'), ('projects', 'Projects'), ('videos', 'Videolar')], max_length=15)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(null=True, upload_to='articles')),
                ('link', models.URLField(blank=True, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Work',
                'verbose_name_plural': 'My Works',
            },
        ),
    ]
