# Generated by Django 3.2.5 on 2021-07-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_uz',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='File'),
        ),
    ]
