# Generated by Django 3.2.4 on 2021-07-26 11:10

from django.db import migrations, models
import my_works.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension]),
        ),
    ]
