# Generated by Django 3.2.5 on 2021-07-31 06:32

from django.db import migrations, models
import my_works.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_works', '0002_auto_20210731_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_uz',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension], verbose_name='File'),
        ),
    ]
