# Generated by Django 3.2.4 on 2021-06-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_works', '0002_myworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='articles'),
        ),
    ]
