# Generated by Django 3.2.5 on 2021-08-03 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_works', '0003_auto_20210731_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'ogg', 'webM'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'ogg', 'webM'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'ogg', 'webM'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_uz',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'ogg', 'webM'])], verbose_name='File'),
        ),
    ]
