# Generated by Django 3.2.4 on 2021-06-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_works', '0003_alter_myworks_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworks',
            name='category',
            field=models.CharField(choices=[('articles', 'Maqolalar'), ('books', 'Kitoblar'), ('events', 'Tadbirlar'), ('presentations', 'Taqdimotlar'), ('projects', 'Loyihalar'), ('videos', 'Videolar')], max_length=15),
        ),
    ]
