# Generated by Django 3.2.4 on 2021-07-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_works', '0003_auto_20210727_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='presentations',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='name_en_us',
            new_name='name_en',
        ),
    ]
