# Generated by Django 3.2.4 on 2021-07-27 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_works.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_works', '0004_auto_20210728_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='articles', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='events',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='events',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='events', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='events',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='presentations', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[my_works.validators.validate_file_extension], verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='Slug'),
        ),
    ]
