# Generated by Django 3.2.4 on 2021-07-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_works', '0004_alter_myworks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='events',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='presentations'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
