# Generated by Django 3.2.4 on 2021-07-28 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_works', '0005_auto_20210728_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='events',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='events',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomi'),
        ),
    ]
